// Copies the built engine, the background data and the scoring module into the
// webapp so the app has a single source of truth for each.
//
// Runs automatically before `npm run dev` and `npm run build`.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP = path.resolve(HERE, "..");
const ROOT = path.resolve(APP, "..");

// The engine is preferred fresh from a local Java build, but falls back to the
// committed prebuilt copy so the app can be built with Node alone — no JDK, no
// Maven and no lib/.
const BUILT_ENGINE = path.join(ROOT, "engine", "target", "js", "cancerin-engine.js");
const PREBUILT_ENGINE = path.join(ROOT, "engine", "prebuilt", "cancerin-engine.js");
const engineSrc = fs.existsSync(BUILT_ENGINE) ? BUILT_ENGINE : PREBUILT_ENGINE;

const COPIES = [
  {
    from: engineSrc,
    to: path.join(APP, "public", "engine", "cancerin-engine.js"),
    hint: "cd engine && mvn -Ppatched,web package",
  },
  {
    from: path.join(ROOT, "data", "background.bin"),
    to: path.join(APP, "public", "data", "background.bin"),
    hint: "node tools/build-data.mjs",
  },
  {
    from: path.join(ROOT, "data", "annotations.json"),
    to: path.join(APP, "public", "data", "annotations.json"),
    hint: "node tools/build-data.mjs",
  },
];

// scoring.mjs is the reference implementation and is already browser-safe (no
// imports). Copy rather than fork so the two can never drift.
const SCORING_SRC = path.join(ROOT, "tools", "scoring.mjs");
const SCORING_DST = path.join(APP, "src", "lib", "scoring.generated.js");

let failed = false;
for (const { from, to, hint } of COPIES) {
  if (!fs.existsSync(from)) {
    console.error(`missing ${path.relative(ROOT, from)}\n  build it with: ${hint}`);
    failed = true;
    continue;
  }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  const kb = (fs.statSync(to).size / 1024).toFixed(0);
  console.log(`  ${path.relative(APP, to)}  (${kb} KB)`);
}

if (!fs.existsSync(SCORING_SRC)) {
  console.error(`missing ${path.relative(ROOT, SCORING_SRC)}`);
  failed = true;
} else {
  const banner = "// GENERATED by scripts/sync-assets.mjs from tools/scoring.mjs. Do not edit.\n";
  fs.mkdirSync(path.dirname(SCORING_DST), { recursive: true });
  fs.writeFileSync(SCORING_DST, banner + fs.readFileSync(SCORING_SRC, "utf8"));
  console.log(`  ${path.relative(APP, SCORING_DST)}`);
}

// Say which engine was used, and flag a locally built one that has drifted from
// the committed copy — that usually means prebuilt/ needs updating before commit.
if (engineSrc === PREBUILT_ENGINE) {
  console.log("  (engine: committed prebuilt copy — no Java build present)");
} else {
  const md5File = PREBUILT_ENGINE + ".md5";
  const recorded = fs.existsSync(md5File) ? fs.readFileSync(md5File, "utf8").trim() : null;
  const actual = crypto.createHash("md5").update(fs.readFileSync(BUILT_ENGINE)).digest("hex");
  if (recorded && recorded !== actual) {
    console.log("  (engine: locally built, DIFFERS from engine/prebuilt — refresh it before committing)");
  } else {
    console.log("  (engine: locally built)");
  }
}

if (failed) process.exit(1);
